services:
  api:
    build:
      context: ./montify-api              # Путь к директории, где лежат pom.xml и src вашего Java-проекта
      dockerfile: Dockerfile # Имя Докерфайла для Java (создадим его ниже)
    container_name: montify_api
    ports:
      - "8080:8080"           # Пробрасываем стандартный порт Spring Boot наружу
    depends_on:
      - redis
      - minio
    restart: always
    env_file:
      - .env # Переопределяем localhost на имена сервисов внутри сети Docker
    environment:
      - REDIS_ADDR=redis:6379
      - MINIO_ENDPOINT=minio:9000
    #environment:
    #  - REDIS_ADDR=redis:6379
    #  - REDIS_QUEUE_NAME=video_render_queue
    #  - MINIO_ENDPOINT=minio:9000
    #  - MINIO_ACCESS_KEY=minioadmin
    #  - MINIO_SECRET_KEY=minioadmin
    #  - MINIO_BUCKET_NAME=video-editor
    #  - MINIO_USE_SSL=false
  media-worker:
    build:
      context: ./media-worker  
      dockerfile: Dockerfile
    container_name: media_worker
    depends_on:
      - redis
      - minio
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_QUEUE_NAME=video_render_queue
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=video-editor
      - MINIO_USE_SSL=false
  redis:
    image: redis:7-alpine
    container_name: redis_media
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: minio_media
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
volumes:
  redis_data:
  minio_data:


  